FROM msr-bpm:latest

# copy the contents of the Process and IS Service Package 
COPY --chown=sagadmin:sagadmin packages/Demo /opt/softwareag/IntegrationServer/packages/Demo
COPY --chown=sagadmin:sagadmin packages/DemoPackage /opt/softwareag/IntegrationServer/packages/DemoPackage